dataset:
  name: VideoDataset
  modality: RGB
  images_path: datasetpath/
  classes: 10
  normalize: True
  padding : False
  dim: [224,224]
  train:
    num_of_frames: 64
  validation:
    num_of_frames: 64
  test:
    num_of_frames: 64
  dataloader:
    train:
      batch_size: 1
      shuffle: True
      num_workers: 2
      pin_memory: True
    validation:
      batch_size: 1
      shuffle: False
      num_workers: 2
    test:
      batch_size: 1
      shuffle: False
      num_workers: 2